Updated base

diff --git a/base/Dockerfile b/base/Dockerfile
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -1,45 +1,37 @@
 FROM debian:buster-slim
-LABEL maintainer=marcio.maciel@evino.com.br \
-      vendor=evino.com.br
+LABEL maintainer=dockerisioner@marciomaciel.com.br \
+      vendor=marciomaciel.com.br
 ENV TERM="xterm-256color" \
     LANG="C.UTF-8" \
     LC_ALL="C.UTF-8" \
     DOCKER_CONF_HOME=/opt/docker/ \
     LOG_STDOUT="" \
     LOG_STDERR=""
+# utils tools
 COPY /bin/ /usr/local/bin/
-RUN set -Eeux; \
+# configs and provisioning scripts
+COPY conf/ /opt/docker/
+RUN set -Ee; \
     chmod +x /usr/local/bin; \
+    chmod +x /opt/docker/bin/*; \
     sed -ri "s/(deb.*\/debian buster main)/\1 contrib non-free /" -- /etc/apt/sources.list; \
     apt-update; \
     apt-upgrade; \
+    # install basic packages
     apt-install \
         apt-transport-https \
         ca-certificates \
         locales \
         procps \
         gnupg \
-        supervisor \
         wget \
         curl \
         vim \
         net-tools \
-        tzdata
-RUN set -Eeux; \
-    wget -O "/sbin/gosu" "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"; \
-    wget -O "/tmp/gosu.asc" "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64.asc"; \
-    export GNUPGHOME="$(mktemp -d)"; \
-    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
-    gpg --batch --verify /tmp/gosu.asc "/sbin/gosu"; \
-    rm -rf "$GNUPGHOME" /tmp/gosu.asc; \
-    chmod +x "sbin/gosu"; \
-    "sbin/gosu" nobody true
-COPY conf/ /opt/docker/
-RUN set -Eeux; \
-    chmod +x /opt/docker/bin/*; \
-    docker-run-bootstrap; \
-    docker-service enable cron; \
-    docker-service enable syslog; \
-    docker-image-cleanup
+        tzdata; \
+    # basic image provisioning
+    run-bootstrap; \
+    # cleanup image before finish setup
+    docker-image-cleaner;
 ENTRYPOINT ["/entrypoint"]
 CMD ["supervisord"]
diff --git a/base/bin/docker-service b/base/bin/docker-service
--- a/base/bin/docker-service
+++ b/base/bin/docker-service
@@ -1,6 +1,6 @@
 #!/bin/bash
-set -o pipefail
-set -Eeux
+# service provisioning
+set -o pipefail -Ee
 if [[ "$#" -le 1 ]]; then
     echo "Usage: $0 <command> <service>"
     exit 1
@@ -8,44 +8,37 @@ fi
 SERVICE_COMMAND=$1
 shift
 for SERVICE in "$@"; do
-    RUN_FILE="/opt/docker/bin/service.d/${SERVICE}.sh"
-    SERVICE_FILE="/opt/docker/etc/supervisor.d/${SERVICE}.conf"
-    PROVISION_FILE="/opt/docker/provision/service.d/${SERVICE}.sh"
+    SERVICE_CONFIG="/opt/docker/etc/supervisor.d/${SERVICE}.conf"
+    SERVICE_PROVISION="/opt/docker/provision/service/${SERVICE}.sh"
     case "$SERVICE_COMMAND" in
         enable)
-            if [[ -f "$PROVISION_FILE" ]]; then
+            if [[ -f "$SERVICE_PROVISION" ]]; then
                 echo "Running provisioning for ${SERVICE}, please wait..."
-                . "$PROVISION_FILE"
-                rm -f -- "$PROVISION_FILE"
+                # shellcheck source=/opt/docker/provision/service/*.sh
+                . "$SERVICE_PROVISION"
+                rm -f -- "$SERVICE_PROVISION"
             fi
-            if [[ -f "$SERVICE_FILE" ]]; then
-                sed -i 's/autostart =.*/autostart = true/g' "$SERVICE_FILE"
+            if [[ -f "$SERVICE_CONFIG" ]]; then
+                sed -i '/autostart =.*/c\autostart = true' "$SERVICE_CONFIG"
             else
-                echo "[ERROR] Service '${SERVICE}' not found (tried ${SERVICE_FILE})"
+                echo "[ERROR] Service '${SERVICE}' not found (tried ${SERVICE_CONFIG})"
                 exit 1
             fi
             ;;
         disable)
-            if [[ -f "$SERVICE_FILE" ]]; then
-                sed -i 's/autostart =.*/autostart = false/g' "$SERVICE_FILE"
+            if [[ -f "$SERVICE_CONFIG" ]]; then
+                sed -i '/autostart =.*/c\autostart = false' "$SERVICE_CONFIG"
             else
-                echo "[ERROR] Service '${SERVICE}' not found (tried ${SERVICE_FILE})"
+                echo "[ERROR] Service '${SERVICE}' not found (tried ${SERVICE_CONFIG})"
                 exit 1
             fi
             ;;
         install)
-             if [[ -f "$PROVISION_FILE" ]]; then
+             if [[ -f "$SERVICE_PROVISION" ]]; then
                 echo "Running provisioning for ${SERVICE}, please wait..."
-                . "$PROVISION_FILE"
-                rm -f -- "$PROVISION_FILE"
-            fi
-            ;;
-        run)
-            if [[ -f "$RUN_FILE" ]]; then
-                exec "$RUN_FILE"
-            else
-                echo "[ERROR] Service '${SERVICE}' not found (tried ${RUN_FILE})"
-                exit 1
+                # shellcheck source=/opt/docker/provision/service/*.sh
+                . "$SERVICE_PROVISION"
+                rm -f -- "$SERVICE_PROVISION"
             fi
             ;;
         stop|start|restart|status|pid|check)
